### ISSUE TITLE
Update the repository URL

### ISSUE THREAD

**Issue by cgarrard** [OpenTreeMap/otm-ecoservice#63]
The URL was updated to github.com/OpenTreeMap/ecoservice in a bunch of files, but that doesn't exist. Should it be github.com/OpenTreeMap/otm-ecoservice instead?

**Comment by maurizi** [comment]
Oh my, thats a mistake.  It should indeed be otm-ecoservice.  Good catch @cgarrad!

Do you know where it is misspelled?  PRs are always appreciated :)

**Comment by cgarrard** [comment]
Looked like it was in a lot of places. I had tons of other stuff to do and didn't try to fix it since it wasn't just one place.

**Comment by RickMohr** [comment]
A github search for `OpenTreeMap/ecoservice` in the repo shows what needs to be fixed.

**Comment by rmiessle** [comment]
I submitted a pull request, I think I got everything updated.

**Comment by maurizi** [comment]
Fixed by https://github.com/OpenTreeMap/otm-ecoservice/pull/64
