### ISSUE TITLE
Invalidate cache of i-Tree code overrides when it becomes stale

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-ecoservice#73]
Possible approach:
- Keep an integer in Redis representing the version of data in the cache
- Increment the version when i-Tree code overrides are created or modified
- All endpoints either take the version as an argument or fetch it from Redis, and refresh the cache if the version is stale

(Thanks to @maurizi for the idea)

**Comment by maurizi** [comment]
This appears to have been fixed by OpenTreeMap/otm-core#2956
